package com.judahben149.tala.domain.mappers

import com.judahben149.tala.data.model.UserEntity
import com.judahben149.tala.domain.models.authentication.SignInMethod
import com.judahben149.tala.domain.models.user.AppUser

fun AppUser.toUserEntity(): UserEntity = UserEntity(
    id = userId,
    email = email,
    isPremiumUser = isPremiumUser,
    displayName = displayName,
    photoUrl = avatarUrl,
    signInMethod = signInMethod.name,
    isEmailVerified = emailVerified,
    firstName = firstName,
    lastName = lastName,
    createdAt = createdAt,
    updatedAt = updatedAt,
    streakDays = streakDays,
    totalConversations = totalConversations,
    learningLanguage = learningLanguage,
    interests = interests,
    currentLevel = currentLevel,
    totalPoints = totalPoints,
    weeklyGoal = weeklyGoal,
    achievementBadges = achievementBadges,
    notificationsEnabled = notificationsEnabled,
    practiceRemindersEnabled = practiceRemindersEnabled,
    selectedVoiceId = selectedVoiceId,
    preferredDifficulty = preferredDifficulty,
    dailyGoalMinutes = dailyGoalMinutes,
    friendsCount = friendsCount,
    isPrivateProfile = isPrivateProfile,
    bio = bio,
    location = location,
    timezone = timezone,
    totalStudyTimeMinutes = totalStudyTimeMinutes,
    favoriteTopics = favoriteTopics,
    lastActiveAt = lastActiveAt,
    loginCount = loginCount
)

fun UserEntity.toAppUser(): AppUser = AppUser(
    userId = id,
    displayName = displayName ?: "",
    email = email,
    isPremiumUser = isPremiumUser,
    signInMethod = SignInMethod.valueOf(signInMethod),
    firstName = firstName ?: "",
    lastName = lastName ?: "",
    avatarUrl = photoUrl,
    emailVerified = isEmailVerified,
    createdAt = createdAt,
    updatedAt = updatedAt,
    streakDays = streakDays,
    totalConversations = totalConversations,
    learningLanguage = learningLanguage,
    interests = interests,
    currentLevel = currentLevel,
    totalPoints = totalPoints,
    weeklyGoal = weeklyGoal,
    achievementBadges = achievementBadges,
    notificationsEnabled = notificationsEnabled,
    practiceRemindersEnabled = practiceRemindersEnabled,
    selectedVoiceId = selectedVoiceId,
    preferredDifficulty = preferredDifficulty,
    dailyGoalMinutes = dailyGoalMinutes,
    friendsCount = friendsCount,
    isPrivateProfile = isPrivateProfile,
    bio = bio,
    location = location,
    timezone = timezone,
    totalStudyTimeMinutes = totalStudyTimeMinutes,
    favoriteTopics = favoriteTopics,
    lastActiveAt = lastActiveAt,
    loginCount = loginCount
)
